export const INITIAL_ORGANIZATION = {
  id: 'org_demo_100',
  name: 'Acme Enterprise Solutions',
  slug: 'acme-corp',
  plan: 'ENTERPRISE',
  currency: 'USD',
  timeZone: 'America/New_York',
};

export const INITIAL_USERS = [
  {
    id: 'user_admin_1',
    name: 'Alex Vance',
    email: 'admin@acme.com',
    role: 'ADMIN',
    jobTitle: 'VP of Sales Operations',
    department: 'Executive',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
  {
    id: 'user_manager_1',
    name: 'Sarah Jenkins',
    email: 'manager@acme.com',
    role: 'MANAGER',
    jobTitle: 'Regional Sales Director',
    department: 'Sales',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
  {
    id: 'user_agent_1',
    name: 'Marcus Chen',
    email: 'agent@acme.com',
    role: 'SALES_AGENT',
    jobTitle: 'Senior Account Executive',
    department: 'Sales',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
  {
    id: 'user_agent_2',
    name: 'Elena Rostova',
    email: 'elena@acme.com',
    role: 'SALES_AGENT',
    jobTitle: 'Account Executive',
    department: 'Sales',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
];

export const INITIAL_COMPANIES = [
  {
    id: 'comp_1',
    name: 'Apex Global Technologies',
    industry: 'FinTech',
    website: 'https://apexglobal.io',
    employees: 450,
    annualRevenue: 45000000,
    phone: '+1 (555) 234-5678',
    email: 'contact@apexglobal.io',
    city: 'New York',
    country: 'USA',
    ownerId: 'user_agent_1',
    ownerName: 'Marcus Chen',
    tags: ['Enterprise', 'High-Value', 'Fintech'],
    dealsCount: 2,
    contactsCount: 3,
    createdAt: '2026-08-01',
  },
  {
    id: 'comp_2',
    name: 'CloudScale Dynamics',
    industry: 'Cloud Infrastructure',
    website: 'https://cloudscale.tech',
    employees: 120,
    annualRevenue: 18000000,
    phone: '+1 (555) 876-5432',
    email: 'info@cloudscale.tech',
    city: 'San Francisco',
    country: 'USA',
    ownerId: 'user_agent_1',
    ownerName: 'Marcus Chen',
    tags: ['SaaS', 'Growth', 'Cloud'],
    dealsCount: 1,
    contactsCount: 2,
    createdAt: '2026-08-10',
  },
  {
    id: 'comp_3',
    name: 'BioGenix Labs',
    industry: 'Healthcare',
    website: 'https://biogenix.org',
    employees: 850,
    annualRevenue: 120000000,
    phone: '+1 (555) 345-6789',
    email: 'partners@biogenix.org',
    city: 'Boston',
    country: 'USA',
    ownerId: 'user_agent_2',
    ownerName: 'Elena Rostova',
    tags: ['Healthcare', 'Compliance', 'Enterprise'],
    dealsCount: 1,
    contactsCount: 1,
    createdAt: '2026-08-15',
  },
  {
    id: 'comp_4',
    name: 'Vanguard Logistics',
    industry: 'Transportation',
    website: 'https://vanguardlogistics.com',
    employees: 230,
    annualRevenue: 28000000,
    phone: '+1 (555) 901-2345',
    email: 'ops@vanguard.com',
    city: 'Chicago',
    country: 'USA',
    ownerId: 'user_manager_1',
    ownerName: 'Sarah Jenkins',
    tags: ['Logistics', 'Closed-Won'],
    dealsCount: 1,
    contactsCount: 1,
    createdAt: '2026-08-20',
  },
];

export const INITIAL_CONTACTS = [
  {
    id: 'cont_1',
    name: 'David Kovac',
    firstName: 'David',
    lastName: 'Kovac',
    email: 'd.kovac@apexglobal.io',
    phone: '+1 (555) 234-5679',
    designation: 'Chief Technology Officer',
    companyId: 'comp_1',
    companyName: 'Apex Global Technologies',
    ownerId: 'user_agent_1',
    ownerName: 'Marcus Chen',
    tags: ['Decision Maker', 'CTO'],
    notes: 'Primary sponsor for multi-tenant upgrade.',
    createdAt: '2026-08-02',
  },
  {
    id: 'cont_2',
    name: 'Rachel Green',
    firstName: 'Rachel',
    lastName: 'Green',
    email: 'rachel@cloudscale.tech',
    phone: '+1 (555) 876-5433',
    designation: 'VP of Product Management',
    companyId: 'comp_2',
    companyName: 'CloudScale Dynamics',
    ownerId: 'user_agent_1',
    ownerName: 'Marcus Chen',
    tags: ['Product Lead'],
    notes: 'Interested in API key integrations.',
    createdAt: '2026-08-11',
  },
  {
    id: 'cont_3',
    name: 'Dr. Aris Thorne',
    firstName: 'Aris',
    lastName: 'Thorne',
    email: 'athorne@biogenix.org',
    phone: '+1 (555) 345-6790',
    designation: 'Head of Clinical Systems',
    companyId: 'comp_3',
    companyName: 'BioGenix Labs',
    ownerId: 'user_agent_2',
    ownerName: 'Elena Rostova',
    tags: ['Buyer', 'Healthcare'],
    notes: 'Requires HIPAA compliance documentation.',
    createdAt: '2026-08-16',
  },
  {
    id: 'cont_4',
    name: 'Michael Scott',
    firstName: 'Michael',
    lastName: 'Scott',
    email: 'mscott@vanguard.com',
    phone: '+1 (555) 901-2346',
    designation: 'Director of Supply Operations',
    companyId: 'comp_4',
    companyName: 'Vanguard Logistics',
    ownerId: 'user_manager_1',
    ownerName: 'Sarah Jenkins',
    tags: ['Operations'],
    notes: 'Signed contract on Aug 28.',
    createdAt: '2026-08-21',
  },
];

export const INITIAL_LEADS = [
  {
    id: 'lead_1',
    firstName: 'Sophia',
    lastName: 'Martine',
    name: 'Sophia Martine',
    email: 'smartine@nexusbiotech.com',
    phone: '+1 (555) 111-2233',
    company: 'Nexus Biotech',
    jobTitle: 'VP Digital Transformation',
    source: 'WEBSITE',
    status: 'QUALIFIED',
    leadScore: 88,
    ownerId: 'user_agent_1',
    ownerName: 'Marcus Chen',
    tags: ['Hot Lead', 'Biotech'],
    notes: 'Requested demo of enterprise workflow automation',
    lastContactedAt: '2026-09-02T14:30:00Z',
    nextFollowUpAt: '2026-09-05T10:00:00Z',
    createdAt: '2026-08-25',
  },
  {
    id: 'lead_2',
    firstName: 'Liam',
    lastName: 'O\'Connor',
    name: 'Liam O\'Connor',
    email: 'liam@finnet-solutions.co',
    phone: '+1 (555) 222-3344',
    company: 'FinNet Solutions',
    jobTitle: 'Head of Procurement',
    source: 'LINKEDIN',
    status: 'PROPOSAL',
    leadScore: 92,
    ownerId: 'user_agent_1',
    ownerName: 'Marcus Chen',
    tags: ['Fintech', 'Priority'],
    notes: 'Budget pre-approved for Q3 software stack update',
    lastContactedAt: '2026-09-03T11:15:00Z',
    nextFollowUpAt: '2026-09-06T14:00:00Z',
    createdAt: '2026-08-26',
  },
  {
    id: 'lead_3',
    firstName: 'Hannah',
    lastName: 'Zhang',
    name: 'Hannah Zhang',
    email: 'hzhang@cyberguard.net',
    phone: '+1 (555) 333-4455',
    company: 'CyberGuard Inc',
    jobTitle: 'Chief Information Officer',
    source: 'REFERRAL',
    status: 'CONTACTED',
    leadScore: 74,
    ownerId: 'user_agent_2',
    ownerName: 'Elena Rostova',
    tags: ['Security', 'High Score'],
    notes: 'Met at Cloud Security Summit 2026',
    lastContactedAt: '2026-09-01T09:00:00Z',
    nextFollowUpAt: '2026-09-08T15:30:00Z',
    createdAt: '2026-08-27',
  },
  {
    id: 'lead_4',
    firstName: 'Carlos',
    lastName: 'Mendez',
    name: 'Carlos Mendez',
    email: 'carlos@solargrid.com',
    phone: '+1 (555) 444-5566',
    company: 'SolarGrid Energy',
    jobTitle: 'Operations Manager',
    source: 'COLD_CALL',
    status: 'NEW',
    leadScore: 45,
    ownerId: 'user_agent_2',
    ownerName: 'Elena Rostova',
    tags: ['CleanTech'],
    notes: 'Inbound inquiry via website form',
    lastContactedAt: null,
    nextFollowUpAt: '2026-09-05T16:00:00Z',
    createdAt: '2026-09-01',
  },
  {
    id: 'lead_5',
    firstName: 'Olivia',
    lastName: 'Taylor',
    name: 'Olivia Taylor',
    email: 'otaylor@omnichannel.org',
    phone: '+1 (555) 555-6677',
    company: 'OmniChannel Retail',
    jobTitle: 'Director of CRM Strategy',
    source: 'INBOUND_DEMO',
    status: 'QUALIFIED',
    leadScore: 85,
    ownerId: 'user_manager_1',
    ownerName: 'Sarah Jenkins',
    tags: ['Retail', 'CRM'],
    notes: 'Evaluating CRM options for 500 sales agents',
    lastContactedAt: '2026-09-03T16:45:00Z',
    nextFollowUpAt: '2026-09-07T11:00:00Z',
    createdAt: '2026-09-02',
  },
];

export const INITIAL_DEALS = [
  {
    id: 'deal_1',
    title: 'Apex Global Enterprise CRM Rollout',
    value: 185000,
    currency: 'USD',
    stage: 'PROPOSAL',
    probability: 75,
    expectedCloseDate: '2026-09-30',
    priority: 'HIGH',
    companyId: 'comp_1',
    companyName: 'Apex Global Technologies',
    contactId: 'cont_1',
    contactName: 'David Kovac',
    ownerId: 'user_agent_1',
    ownerName: 'Marcus Chen',
    tags: ['Q3 Pipeline', 'Enterprise'],
    createdAt: '2026-08-05',
  },
  {
    id: 'deal_2',
    title: 'CloudScale Multi-Tenant Integration',
    value: 92000,
    currency: 'USD',
    stage: 'NEGOTIATION',
    probability: 85,
    expectedCloseDate: '2026-09-20',
    priority: 'HIGH',
    companyId: 'comp_2',
    companyName: 'CloudScale Dynamics',
    contactId: 'cont_2',
    contactName: 'Rachel Green',
    ownerId: 'user_agent_1',
    ownerName: 'Marcus Chen',
    tags: ['Cloud', 'Hot Deal'],
    createdAt: '2026-08-12',
  },
  {
    id: 'deal_3',
    title: 'BioGenix Compliance & Analytics Module',
    value: 240000,
    currency: 'USD',
    stage: 'DEMO',
    probability: 50,
    expectedCloseDate: '2026-10-15',
    priority: 'HIGH',
    companyId: 'comp_3',
    companyName: 'BioGenix Labs',
    contactId: 'cont_3',
    contactName: 'Dr. Aris Thorne',
    ownerId: 'user_agent_2',
    ownerName: 'Elena Rostova',
    tags: ['Healthcare', 'Custom Workflow'],
    createdAt: '2026-08-18',
  },
  {
    id: 'deal_4',
    title: 'Vanguard Fleet Tracking CRM Engine',
    value: 68000,
    currency: 'USD',
    stage: 'WON',
    probability: 100,
    expectedCloseDate: '2026-08-28',
    priority: 'MEDIUM',
    companyId: 'comp_4',
    companyName: 'Vanguard Logistics',
    contactId: 'cont_4',
    contactName: 'Michael Scott',
    ownerId: 'user_manager_1',
    ownerName: 'Sarah Jenkins',
    tags: ['Closed Won'],
    createdAt: '2026-08-22',
  },
  {
    id: 'deal_5',
    title: 'SolarGrid Custom Field Dashboard Engine',
    value: 45000,
    currency: 'USD',
    stage: 'QUALIFIED',
    probability: 30,
    expectedCloseDate: '2026-11-01',
    priority: 'LOW',
    companyId: 'comp_1',
    companyName: 'Apex Global Technologies',
    contactId: 'cont_1',
    contactName: 'David Kovac',
    ownerId: 'user_agent_2',
    ownerName: 'Elena Rostova',
    tags: ['In Pipeline'],
    createdAt: '2026-09-01',
  },
];

export const INITIAL_TASKS = [
  {
    id: 'task_1',
    title: 'Send revised SLA proposal to Apex Global',
    description: 'Include multi-tenant standard data isolation appendix',
    dueDate: '2026-09-05T15:00:00Z',
    priority: 'URGENT',
    status: 'TODO',
    assigneeId: 'user_agent_1',
    assigneeName: 'Marcus Chen',
    relatedEntity: 'DEAL',
    relatedEntityId: 'deal_1',
    relatedName: 'Apex Global Enterprise CRM Rollout',
  },
  {
    id: 'task_2',
    title: 'Follow up with Rachel on CloudScale security approval',
    description: 'Check compliance documentation requirements',
    dueDate: '2026-09-06T11:30:00Z',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    assigneeId: 'user_agent_1',
    assigneeName: 'Marcus Chen',
    relatedEntity: 'CONTACT',
    relatedEntityId: 'cont_2',
    relatedName: 'Rachel Green',
  },
  {
    id: 'task_3',
    title: 'Schedule technical architecture demo with Dr. Thorne',
    description: 'Prepare customized slide deck for healthcare compliance',
    dueDate: '2026-09-08T14:00:00Z',
    priority: 'MEDIUM',
    status: 'TODO',
    assigneeId: 'user_agent_2',
    assigneeName: 'Elena Rostova',
    relatedEntity: 'LEAD',
    relatedEntityId: 'lead_3',
    relatedName: 'Hannah Zhang',
  },
  {
    id: 'task_4',
    title: 'Review quarterly sales performance metrics with team',
    description: 'Prepare Q3 forecast report',
    dueDate: '2026-09-04T17:00:00Z',
    priority: 'HIGH',
    status: 'COMPLETED',
    assigneeId: 'user_manager_1',
    assigneeName: 'Sarah Jenkins',
    relatedEntity: 'USER',
    relatedEntityId: 'user_manager_1',
    relatedName: 'Sarah Jenkins',
  },
];

export const INITIAL_ACTIVITIES = [
  {
    id: 'act_1',
    type: 'MEETING',
    title: 'Executive Demo with CTO David Kovac',
    description: 'Demonstrated multi-tenant security architecture, custom fields system, and real-time dashboard analytics.',
    performedBy: 'Marcus Chen',
    entityType: 'DEAL',
    entityId: 'deal_1',
    entityName: 'Apex Global Enterprise CRM Rollout',
    createdAt: '2026-09-03T15:00:00Z',
  },
  {
    id: 'act_2',
    type: 'EMAIL',
    title: 'Sent Custom Proposal v2.4 to CloudScale',
    description: 'Emailed detailed pricing tiers for 120 user seats with 24/7 dedicated support SLA.',
    performedBy: 'Marcus Chen',
    entityType: 'DEAL',
    entityId: 'deal_2',
    entityName: 'CloudScale Multi-Tenant Integration',
    createdAt: '2026-09-02T11:20:00Z',
  },
  {
    id: 'act_3',
    type: 'CALL',
    title: 'Qualification Call with Sophia Martine',
    description: 'Confirmed budget approval ($150k+), decision timeframe Q3 2026.',
    performedBy: 'Marcus Chen',
    entityType: 'LEAD',
    entityId: 'lead_1',
    entityName: 'Sophia Martine',
    createdAt: '2026-09-01T14:30:00Z',
  },
  {
    id: 'act_4',
    type: 'STATUS_CHANGE',
    title: 'Deal Stage Moved to Won',
    description: 'Vanguard Fleet Tracking deal closed for $68,000 USD total contract value.',
    performedBy: 'Sarah Jenkins',
    entityType: 'DEAL',
    entityId: 'deal_4',
    entityName: 'Vanguard Fleet Tracking CRM Engine',
    createdAt: '2026-08-28T16:00:00Z',
  },
];

export const INITIAL_PRODUCTS = [
  {
    id: 'prod_1',
    name: 'NexusCRM Enterprise Seat',
    sku: 'SKU-NEX-ENT',
    description: 'Full platform seat including deals, AI foundations & analytics',
    category: 'Software',
    price: 99,
    currency: 'USD',
    billingType: 'MONTHLY',
    status: 'ACTIVE',
  },
  {
    id: 'prod_2',
    name: 'Advanced Workflow Automation Pack',
    sku: 'SKU-NEX-WF',
    description: 'Triggers, custom webhook integrations, and rule execution engine',
    category: 'Add-on',
    price: 499,
    currency: 'USD',
    billingType: 'MONTHLY',
    status: 'ACTIVE',
  },
  {
    id: 'prod_3',
    name: 'Dedicated Multi-Tenant SLA & Support',
    sku: 'SKU-NEX-SLA',
    description: '24/7 priority enterprise support and 99.99% uptime guarantee',
    category: 'Services',
    price: 1500,
    currency: 'USD',
    billingType: 'MONTHLY',
    status: 'ACTIVE',
  },
];

export const INITIAL_INVOICES = [
  {
    id: 'inv_1',
    invoiceNumber: 'INV-2026-001',
    companyName: 'Vanguard Logistics',
    customerName: 'Michael Scott',
    dealName: 'Vanguard Fleet Tracking CRM Engine',
    issueDate: '2026-08-28',
    dueDate: '2026-09-28',
    subtotal: 68000,
    tax: 3400,
    discount: 1400,
    total: 70000,
    status: 'PAID',
    notes: 'Thank you for your business! Payment processed via Wire.',
  },
  {
    id: 'inv_2',
    invoiceNumber: 'INV-2026-002',
    companyName: 'CloudScale Dynamics',
    customerName: 'Rachel Green',
    dealName: 'CloudScale Multi-Tenant Integration',
    issueDate: '2026-09-01',
    dueDate: '2026-10-01',
    subtotal: 45000,
    tax: 2250,
    discount: 0,
    total: 47250,
    status: 'SENT',
    notes: 'Net 30 payment terms.',
  },
];

export const INITIAL_WORKFLOWS = [
  {
    id: 'wf_1',
    name: 'High Lead Score Notification Rule',
    trigger: 'Lead status becomes Qualified',
    condition: 'Lead score > 80',
    actions: ['Create High Priority Task', 'Send Real-time Alert to Owner', 'Send Welcome Email'],
    status: 'ACTIVE',
    runsCount: 142,
  },
  {
    id: 'wf_2',
    name: 'Large Deal Escalation Alert',
    trigger: 'Deal value > $100,000',
    condition: 'Stage reaches Proposal',
    actions: ['Notify VP of Sales', 'Add SLA Task for Deal Review'],
    status: 'ACTIVE',
    runsCount: 38,
  },
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif_1',
    title: 'New Lead Assigned',
    message: 'Sophia Martine (Nexus Biotech) was assigned to you.',
    type: 'LEAD_ASSIGNED',
    time: '10 mins ago',
    isRead: false,
  },
  {
    id: 'notif_2',
    title: 'Deal Moved to Proposal',
    message: 'Apex Global Enterprise deal stage updated to PROPOSAL.',
    type: 'DEAL_STAGE_CHANGE',
    time: '2 hours ago',
    isRead: true,
  },
  {
    id: 'notif_3',
    title: 'Payment Received',
    message: 'Invoice INV-2026-001 ($70,000) was marked as PAID.',
    type: 'PAYMENT_RECEIVED',
    time: '1 day ago',
    isRead: false,
  },
];

export const INITIAL_AUDIT_LOGS = [
  {
    id: 'audit_1',
    user: 'Alex Vance (admin@acme.com)',
    action: 'USER_LOGIN',
    entity: 'Authentication',
    details: 'User authenticated via JWT token from 192.168.1.100',
    timestamp: '2026-09-04 10:14:02',
  },
  {
    id: 'audit_2',
    user: 'Marcus Chen (agent@acme.com)',
    action: 'DEAL_UPDATE',
    entity: 'Deal (deal_1)',
    details: 'Changed stage from DEMO to PROPOSAL and updated probability to 75%',
    timestamp: '2026-09-03 15:45:10',
  },
  {
    id: 'audit_3',
    user: 'Sarah Jenkins (manager@acme.com)',
    action: 'LEAD_ASSIGN',
    entity: 'Lead (lead_5)',
    details: 'Reassigned lead Olivia Taylor to Sarah Jenkins',
    timestamp: '2026-09-02 16:30:00',
  },
];

export const INITIAL_CUSTOM_FIELDS = [
  {
    id: 'cf_1',
    entityType: 'LEAD',
    label: 'Budget Range',
    name: 'budget_range',
    type: 'DROPDOWN',
    options: ['$10k - $50k', '$50k - $150k', '$150k+'],
    isRequired: true,
  },
  {
    id: 'cf_2',
    entityType: 'DEAL',
    label: 'Expected Go-Live Date',
    name: 'go_live_date',
    type: 'DATE',
    isRequired: false,
  },
  {
    id: 'cf_3',
    entityType: 'COMPANY',
    label: 'Tech Stack / Infrastructure',
    name: 'tech_stack',
    type: 'TEXT',
    isRequired: false,
  },
];
